### ISSUE TITLE
id 29bit

### ISSUE THREAD

**Issue by msky2009** [autowp/arduino-canhacker#7]
Добрый день! Дмитрий, когда я запускаю Canhacker, то не вижу сообщения c длинными id, только с трехзначными. При использовании Canreadera все ОК. Я использую скорость 33 kbps.

**Comment by autowp** [comment]
А попробуйте установить соединение через терминал (например, putty) и сэмулировать соединение и отправку/приём. Не увидите ли в траффике чего-то подозрительного

**Comment by msky2009** [comment]
В документации описаны дополнительные скорости:
Sa, Sb, Sc, Sd
Планируется ли их поддержка? Или просто можно их дописать в can.h и все будет работать?

**Comment by autowp** [comment]
can.h? Там ничего подобного нет.

https://github.com/autowp/arduino-mcp2515/blob/master/mcp2515.h вот тут перечислены частоты, с которыми теоретически может работать библиотека mcp2515. Глядя на это, можно сказать, что 33.3 и 5 добавить достаточно просто. Под 47.619 и 8.333 конфигурации нет.

Если захотите добавить - я подскажу, что и где доработать, а с вас будет тестирование работы в этих конфигурациях (у меня референсных устройств с такими скоростями нет)

**Comment by msky2009** [comment]
Немного ошибся файлом, т.к. пишу с телефона. У меня машина с SWCAN на 33 kbps. Не могли бы Вы уточнить как симулировать?

В putty подключаемые ком порт и посылаем команды:
C
L
S1

**Comment by msky2009** [comment]
А ещё, как эти скорости можно добавить в Canhacker?

**Comment by autowp** [comment]
ну да, примерно так. L по вкусу
C -> S1 -> O

Canhacker - программу или устройство?
Устройство - перепрошить, модифицировав прошивку.
В программе есть прямой доступ к регистрам скорости. Читая даташат на чип можно подобрать соответствующие скорости значения.

**Comment by msky2009** [comment]
Подключился через putty
Сыпяться 3 фрейма с ид 621, 624, 62C
Но если отправить фрейм с ид, 1043804007 то он срабатывает

**Comment by autowp** [comment]
Что значит "срабатывает"? В ответ вы получаете 29bit сообщения, которые ожидали увидеть в канхакере?

**Comment by msky2009** [comment]
Это команда Mute для магнитолы. В канхантере пусто.

**Comment by autowp** [comment]
Канхакере? вы же через putty подключались

**Comment by msky2009** [comment]
В putty только ид 621 624 и 62с

**Comment by msky2009** [comment]
Странно, перещалил скетч пару раз и заработало
