### ISSUE TITLE
Can.h

### ISSUE THREAD

**Issue by devguyplus** [autowp/arduino-canhacker#8]
I can't find can.h file.

**Comment by autowp** [comment]
Dmitry Pereslegin:
That file is from arduino-mcp2515 library, see installation notes

**Comment by devguyplus** [comment]
Yes, I've noticed.
Thank you.
I also get an error from this line:
canHacker = new CanHacker(interfaceStream, null, SPI_CS_PIN);
"'null' was not declared in this scope"

**Comment by autowp** [comment]
https://www.arduino.cc/en/Reference/SoftwareSerial
